spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://postgresdb:5432/register_manager}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
      #ddl-auto: none
    properties:
      hibernate.format_sql: ${FORMAT_SQL:true}

server:
  port: ${APP_PORT:9090}

management:
  server:
    port: ${MONITORING_PORT:9091}
  endpoints:
    web:
      exposure:
        include: ${MONITORING_LIST:'*'}
logging:
  file:
    name: ${LOG_NAME:register-manager-authorization-server.log}
  level:
    root: ${LOG_LEVEL:warn}
#Trace, debug, info, warn, error

app:
  server:
    #Ambiente docker precisa configurar o nome do servico
    issuer: ${SERVER_ISSUER:http://register-manager-authorization-server:9090}
  token:
    accessTokenExpiration: ${ACCESS_TOKEN_EXPIRATION:30}
    refreshTokenExpiration: ${REFRESH_TOKEN_EXPIRATION:60}