spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/register_manager
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: none
    properties:
      hibernate.format_sql: true

server:
  port: 9090

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: register-manager-authorization-server.log
  level:
    root: warn
#Trace, debug, info, warn, error

app:
  token:
    accessTokenExpiration: 30
    refreshTokenExpiration: 60